export const Strings = {
  appName: 'SeatTime',
  tagline: 'Track your permit driving hours',

  ONBOARDING: {
    WELCOME_HEADLINE: 'Track every mile to your teen\'s license',
    WELCOME_SUBTITLE: 'Log supervised driving hours, track progress toward your state\'s requirement, and generate a DMV-ready log when you\'re done.',
    GET_STARTED: 'Get Started',

    STATE_HEADLINE: 'Which state is your teen learning in?',
    STATE_SEARCH_PLACEHOLDER: 'Search states...',
    STATE_HOURS_LABEL: 'hours required',
    STATE_NO_REQUIREMENT: 'No hour requirement',
    STATE_CONTINUE: 'Continue',

    TEEN_NAME_HEADLINE: 'What\'s your teen\'s name?',
    TEEN_NAME_PLACEHOLDER: 'First name',
    TEEN_NAME_CONTINUE: 'Continue',

    READY_HEADLINE: 'You\'re all set!',
    READY_REQUIREMENT: (state: string, total: number, night: number) =>
      `${state} requires ${total} total hours${night > 0 ? ` (${night} at night)` : ''}`,
    READY_NO_REQUIREMENT: (state: string) =>
      `${state} doesn't require logged hours, but tracking practice is still a great idea!`,
    START_TRACKING: 'Start Tracking',
  },

  DRIVE: {
    START_DRIVE: 'Start Drive',
    LOG_PAST_DRIVE: 'Log Past Drive',
    END_DRIVE: 'End Drive',
    END_DRIVE_CONFIRM_TITLE: 'End this drive?',
    END_DRIVE_CONFIRM_MESSAGE: 'This will save your drive session.',
    END_DRIVE_CONFIRM_YES: 'Save Drive',
    END_DRIVE_CONFIRM_NO: 'Keep Driving',
    TIMER_LABEL: 'Drive Time',
    DISTANCE_LABEL: 'mi',
    SPEED_LABEL: 'mph',
    CONDITIONS_LABEL: 'Conditions',
    TIME_OF_DAY_DAY: 'Day',
    TIME_OF_DAY_NIGHT: 'Night',
    WEATHER_CLEAR: 'Clear',
    WEATHER_RAIN: 'Rain',
    WEATHER_SNOW: 'Snow',
    WEATHER_FOG: 'Fog',
    ROAD_RESIDENTIAL: 'Residential',
    ROAD_HIGHWAY: 'Highway',
    ROAD_RURAL: 'Rural',
    ROAD_PARKING: 'Parking Lot',
    LOCATION_PERMISSION_TITLE: 'Location Access',
    LOCATION_PERMISSION_MESSAGE: 'SeatTime uses your location to track your driving route. This helps create an accurate log of each practice drive.',
    MANUAL_LOG_TITLE: 'Log a Past Drive',
    MANUAL_DATE_LABEL: 'Date',
    MANUAL_HOURS_LABEL: 'Hours',
    MANUAL_MINUTES_LABEL: 'Minutes',
    MANUAL_SAVE: 'Save Drive',
    DRIVE_SAVED: 'Drive saved!',
    NO_DRIVES_YET: 'No drives logged yet',
    NO_DRIVES_SUBTITLE: 'Start your first practice drive or log a past one.',
  },

  DRIVE_COMPLETE: {
    HERO: (name: string) => `Nice work, ${name}!`,
    HERO_FALLBACK: 'Nice work!',
    DRIVE_STATS: 'Drive Stats',
    DURATION: 'Duration',
    DISTANCE: 'Distance',
    CONDITIONS: 'Conditions',
    TIME: 'Time',
    MILES: 'mi',
    PROGRESS: 'Overall Progress',
    HOURS_REMAINING: (hours: number) => `${hours.toFixed(1)} hours remaining`,
    NIGHT_PROGRESS: 'Night Progress',
    NIGHT_REMAINING: (hours: number) => `${hours.toFixed(1)} night hours remaining`,
    COMPLETE: 'All hours complete!',
    DONE: 'Done',
  },

  PROGRESS: {
    TITLE: 'Progress',
    HOURS_OF: (current: number, total: number) => `${current}h of ${total}h`,
    DAY_HOURS: 'Day',
    NIGHT_HOURS: 'Night',
    HOURS_FRACTION: (current: number, total: number) => `${current}h / ${total}h`,
    THIS_WEEK: 'This Week',
    WEEKLY_HOURS: (hours: number) => `${hours} hours this week`,
    MILESTONES: 'Milestones',
    MILESTONE_25: 'Quarter Way There',
    MILESTONE_50: 'Halfway!',
    MILESTONE_75: 'Almost There',
    MILESTONE_100: 'Ready for the Road!',
    MILESTONE_ACHIEVED: 'Achieved',
    MILESTONE_LOCKED: 'Locked',
    PROJECTION_TITLE: 'Estimated Completion',
    PROJECTION: (name: string, date: string) =>
      `At your current pace, ${name} will be ready by ${date}.`,
    PROJECTION_EMPTY: 'Start driving to see your projection.',
    PROJECTION_DONE: 'All required hours complete!',
    STATS: 'Stats',
    TOTAL_DRIVES: 'Total Drives',
    AVG_DURATION: 'Avg Duration',
    LONGEST_DRIVE: 'Longest Drive',
    STREAK: 'Current Streak',
    MINUTES: 'min',
    DAYS: (n: number) => `${n} day${n === 1 ? '' : 's'}`,
    NO_REQUIREMENT: 'Your state has no hour requirement — keep practicing!',
  },

  HISTORY: {
    TITLE: 'Drive History',
    DRIVE_COUNT: (count: number) => `${count} drive${count === 1 ? '' : 's'} logged`,
    FILTER_ALL: 'All',
    FILTER_DAY: 'Day',
    FILTER_NIGHT: 'Night',
    FILTER_HIGHWAY: 'Highway',
    FILTER_RESIDENTIAL: 'Residential',
    FILTER_RURAL: 'Rural',
    FILTER_PARKING: 'Parking Lot',
    FILTER_MANUAL: 'Manual',
    SUMMARY: (totalHours: number, nightHours: number) =>
      `Total: ${totalHours} hours · ${nightHours} night hours`,
    EMPTY_ALL: 'No drives logged yet',
    EMPTY_DAY: 'No day drives yet',
    EMPTY_NIGHT: 'No night drives yet',
    EMPTY_HIGHWAY: 'No highway drives logged',
    EMPTY_RESIDENTIAL: 'No residential drives logged',
    EMPTY_RURAL: 'No rural drives logged',
    EMPTY_PARKING: 'No parking lot drives logged',
    EMPTY_MANUAL: 'No manual entries yet',
    EMPTY_SUBTITLE: 'Drives matching this filter will appear here.',
    TIME_RANGE: (start: string, end: string) => `${start} — ${end}`,
    MANUAL_ENTRY: 'Manual entry',
  },

  SETTINGS: {
    TITLE: 'Settings',
    TEEN_PROFILE: 'Teen Profile',
    TEEN_NAME: 'Name',
    STATE: 'State',
    CHANGE_STATE: 'Change State',
    HOURS_REQUIRED: (n: number) => `${n} hours required`,
    NO_REQUIREMENT: 'No requirement',
    FAMILY: 'Family',
    INVITE_COPARENT: 'Invite Co-Parent',
    INVITE_DESC: 'Share driving logs with another parent or guardian',
    MANAGE_FAMILY: 'Manage Family',
    COMING_SOON: 'Coming Soon',
    COMING_SOON_MSG: 'This feature is coming in a future update.',
    DATA: 'Data & Export',
    EXPORT_PDF: 'Export PDF for DMV',
    EXPORT_PDF_DESC: 'Professional driving log for your DMV appointment',
    EXPORT_PDF_ERROR: 'Failed to generate PDF. Please try again.',
    EXPORT_JSON: 'Export Drive Data',
    EXPORT_JSON_DESC: 'Share all drive sessions as a JSON file',
    EXPORT_SUCCESS: 'Data exported successfully',
    EXPORT_EMPTY: 'No drives to export yet.',
    APP: 'App',
    APPEARANCE: 'Appearance',
    APPEARANCE_LIGHT: 'Light',
    APPEARANCE_DARK: 'Dark',
    APPEARANCE_SYSTEM: 'System',
    ABOUT: 'About SeatTime',
    VERSION: 'Version 1.0.0',
    PRIVACY_POLICY: 'Privacy Policy',
    TERMS: 'Terms of Service',
    RATE: 'Rate SeatTime',
    RATE_UNAVAILABLE: 'Reviews are available on the App Store and Google Play.',
    SUPPORT: 'Contact Support',
    SUPPORT_EMAIL: 'dan@listinglab.pro',
    DANGER: 'Danger Zone',
    DELETE_DATA: 'Delete All Driving Data',
    DELETE_CONFIRM_TITLE: 'Delete All Data?',
    DELETE_CONFIRM_MSG: (count: number) =>
      `This cannot be undone. All ${count} drive${count === 1 ? '' : 's'} will be permanently deleted.`,
    DELETE_CONFIRM_YES: 'Delete Everything',
    DELETE_CONFIRM_NO: 'Cancel',
    RESET_APP: 'Reset App',
    RESET_CONFIRM_TITLE: 'Reset SeatTime?',
    RESET_CONFIRM_MSG: 'This will delete all data and return to the setup screen. This cannot be undone.',
    RESET_CONFIRM_YES: 'Reset Everything',
    RESET_CONFIRM_NO: 'Cancel',
    RESET_DOUBLE_TITLE: 'Are you absolutely sure?',
    RESET_DOUBLE_MSG: 'All driving data, profile, and settings will be permanently deleted.',
    SAVED: 'Saved',
  },

  AUTH: {
    TITLE: 'SeatTime',
    SUBTITLE: 'Track your teen\'s driving hours',
    SIGN_IN: 'Sign In',
    CREATE_ACCOUNT: 'Create Account',
    SIGN_IN_WITH_APPLE: 'Sign in with Apple',
    EMAIL_PLACEHOLDER: 'Email address',
    PASSWORD_PLACEHOLDER: 'Password',
    OR_DIVIDER: 'or',
    SKIP_FOR_NOW: 'Skip for now',
    SWITCH_TO_SIGN_UP: 'Need an account? Create one',
    SWITCH_TO_SIGN_IN: 'Have an account? Sign in',
    ERROR_INVALID_EMAIL: 'Please enter a valid email address.',
    ERROR_WEAK_PASSWORD: 'Password must be at least 6 characters.',
    ERROR_USER_NOT_FOUND: 'No account found with that email.',
    ERROR_WRONG_PASSWORD: 'Incorrect password. Please try again.',
    ERROR_EMAIL_IN_USE: 'An account already exists with that email.',
    ERROR_GENERIC: 'Something went wrong. Please try again.',
    SIGNING_IN: 'Signing in...',
    CREATING_ACCOUNT: 'Creating account...',
  },

  FAMILY: {
    INVITE_TITLE: 'Invite Co-Parent',
    INVITE_SUBTITLE: 'Share this code with another parent or guardian to sync driving logs.',
    INVITE_CODE_LABEL: 'Invite Code',
    INVITE_SHARE: 'Share Code',
    INVITE_COPY: 'Copy Code',
    INVITE_COPIED: 'Copied!',
    INVITE_EXPIRES: 'Expires in 7 days',
    INVITE_GENERATING: 'Generating code...',
    JOIN_TITLE: 'Join Family',
    JOIN_SUBTITLE: 'Enter the 6-character code from your co-parent.',
    JOIN_PLACEHOLDER: 'Enter code',
    JOIN_BUTTON: 'Join',
    JOIN_INVALID: 'Invalid or expired code. Please try again.',
    JOIN_SUCCESS: 'You\'ve joined the family! Syncing drives now.',
    MEMBERS_TITLE: 'Family Members',
    MEMBER_CREATOR: 'Creator',
    MEMBER_REMOVE: 'Remove',
    MEMBER_REMOVE_CONFIRM_TITLE: 'Remove Member?',
    MEMBER_REMOVE_CONFIRM_MSG: 'They will no longer see shared driving data.',
    SIGN_IN_REQUIRED: 'Sign in to share with co-parent',
    SIGN_IN_PROMPT: 'Sign In',
    SYNCED: 'Synced',
    SYNCING: 'Syncing...',
    OFFLINE: 'Offline',
    ACCOUNT: 'Account',
    SIGNED_IN_AS: 'Signed in as',
    SIGN_OUT: 'Sign Out',
  },

  HOME: {
    GREETING: (name: string) => `Welcome back`,
    GREETING_FIRST: (name: string) => `Let's get started, ${name}!`,
    PROGRESS_OF: (current: number, total: number) => `${current} of ${total} hours complete`,
    DAY_HOURS: 'Day',
    NIGHT_HOURS: 'Night',
    HOURS_FRACTION: (current: number, total: number) => `${current}h / ${total}h`,
    RECENT_DRIVES: 'Recent Drives',
    SEE_ALL: 'See All',
    EMPTY_TITLE: 'No drives yet',
    EMPTY_SUBTITLE: 'Start your first practice drive or log a past one to see your progress here.',
    START_DRIVE: 'Start Drive',
    LOG_PAST_DRIVE: 'Log Past Drive',
  },

  ERROR: {
    TITLE: 'Something went wrong',
    REASSURANCE: "Don't worry — your driving data is safe. Try restarting the screen or the app.",
    TRY_AGAIN: 'Try Again',
    RESTART: 'Restart App',
    DEV_DETAILS: 'Error Details',
  },
} as const;
